### ISSUE TITLE
DEV-6: Model selection with grid search

### ISSUE THREAD

**Issue by TetianaKlymchuk** [TetianaKlymchuk/NN-Model-Templates#6]
Grid search for regression should include:

- _importing all necessary libraries_;
- _initial loading_;
- _feature scaling_ ;
- _a function that builds a regressor_;
- _defining a grid search based on parameters of regressor_ (different optimizers, units, kernel initializers, loss, ets);
- _evaluating the performance by showing best parameters and best accuracy of grid search_.

To work on this issue, please use a branch **DEV-6** created from **devel**. When the work is finished - create a PR to the **devel** branch. At the end of each development circles, code from the **devel** branch (if everything is ok) goes to the **master** branch.

**Comment by KovDimaY** [comment]
I am going to take this one! :)
