### ISSUE TITLE
DEV-7: Model selection with cross validation

### ISSUE THREAD

**Issue by TetianaKlymchuk** [TetianaKlymchuk/NN-Model-Templates#7]
Grid search for regression should include:

- _importing all necessary libraries_;
- _initial loading_;
- _feature scaling_ ;
- _a function that builds a regressor_;
- _defining a cross validation search_;
- _visualizing results_.

To work on this issue, please use a branch **DEV-7** created from **devel**. When the work is finished - create a PR to the **devel** branch. At the end of each development circles, code from the **devel** branch (if everything is ok) goes to the **master** branch.

**Comment by KovDimaY** [comment]
I am going to take this one too
